export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'


export const MOVIE_DETAILS_LIST_REQUEST = 'MOVIE_DETAILS_LIST_REQEST'
export const MOVIE_DETAILS_LIST_SUCCESS = 'MOVIE_DETAILS_LIST_SUCCESS'
export const MOVIE_DETAILS_LIST_FAIL = 'MOVIE_DETAILS_LIST_FAIL'