export const TV_LIST_REQUEST = 'TV_LIST_REQEST'
export const TV_LIST_SUCCESS = 'TV_LIST_SUCCESS'
export const TV_LIST_FAIL = 'TV_LIST_FAIL'


export const TV_DETAILS_LIST_REQUEST = 'TV_DETAILS_LIST_REQEST'
export const TV_DETAILS_LIST_SUCCESS = 'TV_DETAILS_LIST_SUCCESS'
export const TV_DETAILS_LIST_FAIL = 'TV_DETAILS_LIST_FAIL'